---
title: "R Notebook"
output: html_notebook
---
Variable Independiente -> Contexto Político Nacional
1. 
```{r}
library(htmltab) 

linkCIA_demo = "https://en.wikipedia.org/wiki/Democracy_Index"
linkPath_demo='//*[@id="mw-content-text"]/div[1]/table[2]'

IndiceDemo = htmltab(doc = linkCIA_demo, 
                which =linkPath_demo)
```
1.1. Limpieza de base
```{r}
library(stringr)
names(IndiceDemo)
names(IndiceDemo)=str_split(string = names(IndiceDemo),
                pattern = ' ',
                simplify = T)[,1]
IndiceDemo$Changes=NULL
IndiceDemo$Rank=NULL
IndiceDemo[,]=lapply(IndiceDemo[,], trimws,whitespace = "[\\h\\v]")
head(IndiceDemo)
```
```{r}
library(dplyr)
Demo=IndiceDemo %>% arrange(Country)
head(Demo)
```
```{r}
Demo[,c(2,4,8,9)]=NULL
head(Demo)
```
```{r}
Demo[,-1]=lapply(Demo[,-1], as.numeric)
str(Demo)
```

2.
```{r}
library(htmltab)
linkCIA_free= "https://en.wikipedia.org/wiki/Freedom_in_the_World"
linkPath_free='//*[@id="mw-content-text"]/div[1]/table[1]'

IndiceLibertad = htmltab(doc = linkCIA_free, 
                which =linkPath_free)
```

```{r}
names(IndiceLibertad)
str(IndiceLibertad)
```

```{r}
IndiceLibertad[,c(-1,-14,-15,-16,-17)]=NULL
IndiceLibertad[,c(2)]=NULL
names(IndiceLibertad)[1]="Country"
names(IndiceLibertad)[2]="DerechosPolíticos2019"
names(IndiceLibertad)[3]="LibertadCivil2019"
names(IndiceLibertad)[4]="Libertad"
head(IndiceLibertad)
```


```{r}
str(IndiceLibertad)
```
```{r}
names(IndiceLibertad)
```


```{r}
IndiceLibertad$Country=gsub('\\*','',IndiceLibertad$Country)
head(IndiceLibertad)
```

```{r}
IndiceLibertad[,c(3,4)]=NULL
str(IndiceLibertad)
```
3.
```{r}
library(rio)
library(import)
lkXLSX2="https://github.com/Xiomara20180370/Xiomararepositorio-/raw/master/Data_Extract_From_Worldwide_Governance_Indicators.xlsx"
Conflictos=import(lkXLSX2)
```

```{r}
names(Conflictos)
```
```{r}
Conflictos[,c(2,3,4)]=NULL
head(Conflictos)
```
```{r}
names(Conflictos)[1]="Country"
names(Conflictos)[2]="EstabilidadPolítica"
```

```{r}
Conflictos$EstabilidadPolítica = as.numeric(Conflictos$EstabilidadPolítica)
str(Conflictos)
```
MERGE
```{r}
BaseFinal=merge(Conflictos,Demo,by.x='Country', by.y='Country')
BaseFinal[duplicated(BaseFinal$Country),]
BaseFinal[!complete.cases(BaseFinal$Country),]
```

```{r}
write.csv(BaseFinal,"VariableContextoPolítico.csv", row.names = F)
```




